import type { EquipmentId, FlavorVector, Ingredient } from '../src/domain/types.ts';
import { EQUIPMENT_IDS } from '../src/domain/types.ts';

export type IngredientDef = {
  id: string;
  name: string;
  category: string;
  equipmentId: EquipmentId;
  flavor: FlavorVector;
  compoundIds: string[];
  newGameStarter?: boolean;
  softResetStarter?: boolean;
};

/**
 * Builds a full FlavorVector from the axes that actually matter for an
 * ingredient; every unlisted continuous axis is 0 and TE defaults to ambient.
 */
function flavor(axes: Partial<FlavorVector>): FlavorVector {
  return {
    SW: 0,
    SA: 0,
    SO: 0,
    BI: 0,
    UM: 0,
    HE: 0,
    FR: 0,
    EA: 0,
    SM: 0,
    PU: 0,
    NU: 0,
    RI: 0,
    LI: 0,
    HT: 0,
    CR: 0,
    ...axes,
    TE: axes.TE ?? 0,
  };
}

export const INGREDIENT_DEFINITIONS: IngredientDef[] = [
  // ---------------------------------------------------------------- prep_station (12)
  {
    id: 'flour',
    name: 'Flour',
    category: 'grain',
    equipmentId: 'prep_station',
    flavor: flavor({ SW: 1, EA: 2, NU: 2, RI: 1, LI: 2 }),
    compoundIds: ['c_grain', 'c_starch'],
    newGameStarter: true,
    softResetStarter: true,
  },
  {
    id: 'salt',
    name: 'Salt',
    category: 'seasoning',
    equipmentId: 'prep_station',
    flavor: flavor({ SA: 10, CR: 1 }),
    compoundIds: ['c_mineral', 'c_umami_base'],
    newGameStarter: true,
    softResetStarter: true,
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'dairy',
    equipmentId: 'prep_station',
    flavor: flavor({ SW: 2, SA: 2, UM: 2, NU: 2, RI: 9 }),
    compoundIds: ['c_dairy_lactone', 'c_fat'],
    newGameStarter: true,
    softResetStarter: true,
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'vegetable',
    equipmentId: 'prep_station',
    flavor: flavor({ SW: 3, SO: 1, UM: 3, EA: 2, PU: 8, CR: 4 }),
    compoundIds: ['c_allium', 'c_sulfur'],
    newGameStarter: true,
    softResetStarter: true,
  },
  {
    id: 'chicken',
    name: 'Chicken Breast',
    category: 'protein',
    equipmentId: 'prep_station',
    flavor: flavor({ SA: 2, UM: 9, RI: 6, LI: 2, TE: 1 }),
    compoundIds: ['c_poultry', 'c_maillard', 'c_umami_base'],
    newGameStarter: true,
    softResetStarter: true,
  },
  {
    id: 'garlic',
    name: 'Garlic',
    category: 'aromatic',
    equipmentId: 'prep_station',
    flavor: flavor({ SW: 1, UM: 5, EA: 1, PU: 10, HT: 2 }),
    compoundIds: ['c_allium', 'c_sulfur', 'c_umami_base'],
    newGameStarter: true,
  },
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    category: 'fat',
    equipmentId: 'prep_station',
    flavor: flavor({ BI: 2, HE: 2, FR: 2, PU: 1, RI: 7 }),
    compoundIds: ['c_fat', 'c_green_note'],
    newGameStarter: true,
  },
  {
    id: 'rice',
    name: 'Rice',
    category: 'grain',
    equipmentId: 'prep_station',
    flavor: flavor({ SW: 2, EA: 1, NU: 2, LI: 4, TE: 1 }),
    compoundIds: ['c_grain', 'c_starch'],
    newGameStarter: true,
  },
  {
    id: 'egg',
    name: 'Egg',
    category: 'protein',
    equipmentId: 'prep_station',
    flavor: flavor({ SA: 1, UM: 4, RI: 5 }),
    compoundIds: ['c_egg', 'c_sulfur'],
    newGameStarter: true,
  },
  {
    id: 'black_pepper',
    name: 'Black Pepper',
    category: 'spice',
    equipmentId: 'prep_station',
    flavor: flavor({ BI: 2, HE: 2, EA: 1, PU: 6, HT: 4 }),
    compoundIds: ['c_pepper', 'c_terpene'],
  },
  {
    id: 'vegetable_broth',
    name: 'Vegetable Broth',
    category: 'liquid',
    equipmentId: 'prep_station',
    flavor: flavor({ SA: 3, UM: 4, HE: 2, EA: 3, LI: 4, TE: 1 }),
    compoundIds: ['c_broth', 'c_umami_base', 'c_green_note'],
  },
  {
    id: 'lemon',
    name: 'Lemon',
    category: 'citrus',
    equipmentId: 'prep_station',
    flavor: flavor({ SW: 1, SO: 9, BI: 2, FR: 6, LI: 5 }),
    compoundIds: ['c_citrus', 'c_terpene'],
  },

  // ---------------------------------------------------------------- grill (8)
  {
    id: 'beef_steak',
    name: 'Beef Steak',
    category: 'protein',
    equipmentId: 'grill',
    flavor: flavor({ SA: 2, UM: 8, SM: 3, RI: 7, TE: 1 }),
    compoundIds: ['c_beef', 'c_maillard', 'c_fat'],
  },
  {
    id: 'pork_chop',
    name: 'Pork Chop',
    category: 'protein',
    equipmentId: 'grill',
    flavor: flavor({ SW: 2, SA: 2, UM: 6, SM: 2, RI: 6, TE: 1 }),
    compoundIds: ['c_pork', 'c_maillard', 'c_fat'],
  },
  {
    id: 'lamb_chop',
    name: 'Lamb Chop',
    category: 'protein',
    equipmentId: 'grill',
    flavor: flavor({ SA: 2, UM: 7, HE: 2, EA: 3, SM: 2, RI: 7, TE: 1 }),
    compoundIds: ['c_lamb', 'c_maillard', 'c_fat'],
  },
  {
    id: 'bell_pepper',
    name: 'Bell Pepper',
    category: 'vegetable',
    equipmentId: 'grill',
    flavor: flavor({ SW: 4, HE: 2, FR: 3, EA: 1, LI: 4, CR: 6, TE: 1 }),
    compoundIds: ['c_capsicum', 'c_green_note'],
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    category: 'vegetable',
    equipmentId: 'grill',
    flavor: flavor({ SW: 2, HE: 1, EA: 2, LI: 6, CR: 4, TE: 1 }),
    compoundIds: ['c_cucurbit', 'c_green_note'],
  },
  {
    id: 'corn',
    name: 'Sweet Corn',
    category: 'vegetable',
    equipmentId: 'grill',
    flavor: flavor({ SW: 7, UM: 2, NU: 2, LI: 3, CR: 5, TE: 1 }),
    compoundIds: ['c_grain', 'c_maillard', 'c_starch'],
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    category: 'vegetable',
    equipmentId: 'grill',
    flavor: flavor({ BI: 3, UM: 4, EA: 4, SM: 2, RI: 3, TE: 1 }),
    compoundIds: ['c_nightshade', 'c_earthy_note'],
  },
  {
    id: 'portobello_mushroom',
    name: 'Portobello Mushroom',
    category: 'vegetable',
    equipmentId: 'grill',
    flavor: flavor({ UM: 8, EA: 6, SM: 1, RI: 3, TE: 1 }),
    compoundIds: ['c_mushroom', 'c_umami_base', 'c_earthy_note'],
  },

  // ---------------------------------------------------------------- oven (9)
  {
    id: 'bread',
    name: 'Bread',
    category: 'grain',
    equipmentId: 'oven',
    flavor: flavor({ SW: 2, UM: 1, EA: 2, NU: 3, RI: 2, CR: 5, TE: 1 }),
    compoundIds: ['c_grain', 'c_maillard', 'c_yeast'],
  },
  {
    id: 'potato',
    name: 'Baked Potato',
    category: 'vegetable',
    equipmentId: 'oven',
    flavor: flavor({ SW: 2, EA: 5, NU: 2, RI: 2, LI: 2, TE: 1 }),
    compoundIds: ['c_starch', 'c_earthy_note'],
  },
  {
    id: 'sweet_potato',
    name: 'Sweet Potato',
    category: 'vegetable',
    equipmentId: 'oven',
    flavor: flavor({ SW: 7, EA: 4, NU: 2, RI: 3, TE: 1 }),
    compoundIds: ['c_starch', 'c_earthy_note', 'c_caramel'],
  },
  {
    id: 'salmon_fillet',
    name: 'Salmon Fillet',
    category: 'seafood',
    equipmentId: 'oven',
    flavor: flavor({ SA: 1, UM: 7, SM: 2, RI: 6, LI: 2, TE: 1 }),
    compoundIds: ['c_seafood', 'c_marine', 'c_fat'],
  },
  {
    id: 'chicken_thigh',
    name: 'Chicken Thigh',
    category: 'protein',
    equipmentId: 'oven',
    flavor: flavor({ SA: 1, UM: 7, SM: 1, RI: 6, TE: 1 }),
    compoundIds: ['c_poultry', 'c_maillard', 'c_fat'],
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'vegetable',
    equipmentId: 'oven',
    flavor: flavor({ SW: 6, HE: 1, EA: 4, LI: 3, CR: 6, TE: 1 }),
    compoundIds: ['c_terpene', 'c_earthy_note', 'c_caramel'],
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'vegetable',
    equipmentId: 'oven',
    flavor: flavor({ BI: 4, UM: 2, HE: 2, EA: 3, LI: 3, CR: 5, TE: 1 }),
    compoundIds: ['c_brassica', 'c_sulfur', 'c_green_note'],
  },
  {
    id: 'cheddar',
    name: 'Cheddar',
    category: 'dairy',
    equipmentId: 'oven',
    flavor: flavor({ SA: 6, SO: 2, UM: 7, NU: 2, RI: 7 }),
    compoundIds: ['c_dairy_lactone', 'c_aged_ferment', 'c_fat'],
  },
  {
    id: 'bacon',
    name: 'Bacon',
    category: 'protein',
    equipmentId: 'oven',
    flavor: flavor({ SW: 2, SA: 8, UM: 7, SM: 8, RI: 7, CR: 5, TE: 1 }),
    compoundIds: ['c_pork', 'c_smoke', 'c_maillard'],
  },

  // ---------------------------------------------------------------- fryer (7)
  {
    id: 'chicken_wing',
    name: 'Chicken Wing',
    category: 'protein',
    equipmentId: 'fryer',
    flavor: flavor({ SA: 3, UM: 6, RI: 6, CR: 7, TE: 1 }),
    compoundIds: ['c_poultry', 'c_maillard', 'c_fried'],
  },
  {
    id: 'potato_fries',
    name: 'Potato Fries',
    category: 'vegetable',
    equipmentId: 'fryer',
    flavor: flavor({ SW: 1, SA: 5, EA: 3, RI: 4, CR: 8, TE: 1 }),
    compoundIds: ['c_starch', 'c_fried', 'c_maillard'],
  },
  {
    id: 'calamari',
    name: 'Calamari',
    category: 'seafood',
    equipmentId: 'fryer',
    flavor: flavor({ SA: 2, UM: 5, RI: 2, LI: 3, CR: 6, TE: 1 }),
    compoundIds: ['c_seafood', 'c_marine', 'c_fried'],
  },
  {
    id: 'tempura_shrimp',
    name: 'Tempura Shrimp',
    category: 'seafood',
    equipmentId: 'fryer',
    flavor: flavor({ SW: 3, SA: 2, UM: 6, LI: 3, CR: 8, TE: 1 }),
    compoundIds: ['c_seafood', 'c_marine', 'c_fried'],
  },
  {
    id: 'falafel',
    name: 'Falafel',
    category: 'legume',
    equipmentId: 'fryer',
    flavor: flavor({ UM: 3, HE: 3, EA: 5, PU: 2, NU: 4, CR: 7, TE: 1 }),
    compoundIds: ['c_legume', 'c_fried', 'c_warm_spice'],
  },
  {
    id: 'yeast_doughnut',
    name: 'Yeast Doughnut',
    category: 'pastry',
    equipmentId: 'fryer',
    flavor: flavor({ SW: 8, NU: 2, RI: 6, CR: 4, TE: 1 }),
    compoundIds: ['c_yeast', 'c_caramel', 'c_fried'],
  },
  {
    id: 'plantain',
    name: 'Fried Plantain',
    category: 'fruit',
    equipmentId: 'fryer',
    flavor: flavor({ SW: 6, FR: 5, EA: 2, RI: 3, CR: 3, TE: 1 }),
    compoundIds: ['c_tropical', 'c_starch', 'c_fried'],
  },

  // ---------------------------------------------------------------- stockpot (9)
  {
    id: 'pasta',
    name: 'Pasta',
    category: 'grain',
    equipmentId: 'stockpot',
    flavor: flavor({ SW: 1, UM: 1, EA: 1, NU: 2, LI: 3, TE: 1 }),
    compoundIds: ['c_grain', 'c_starch'],
  },
  {
    id: 'lentils',
    name: 'Lentils',
    category: 'legume',
    equipmentId: 'stockpot',
    flavor: flavor({ UM: 3, EA: 6, NU: 3, RI: 2, TE: 1 }),
    compoundIds: ['c_legume', 'c_earthy_note'],
  },
  {
    id: 'chickpeas',
    name: 'Chickpeas',
    category: 'legume',
    equipmentId: 'stockpot',
    flavor: flavor({ SW: 2, UM: 2, EA: 4, NU: 5, RI: 2, TE: 1 }),
    compoundIds: ['c_legume', 'c_nutty_note', 'c_starch'],
  },
  {
    id: 'tomato_paste',
    name: 'Tomato Paste',
    category: 'vegetable',
    equipmentId: 'stockpot',
    flavor: flavor({ SW: 4, SO: 5, UM: 8, EA: 2, RI: 3, TE: 1 }),
    compoundIds: ['c_nightshade', 'c_umami_base', 'c_caramel'],
  },
  {
    id: 'celery',
    name: 'Celery',
    category: 'vegetable',
    equipmentId: 'stockpot',
    flavor: flavor({ SA: 2, BI: 2, UM: 1, HE: 5, LI: 6, CR: 7 }),
    compoundIds: ['c_green_note', 'c_terpene', 'c_broth'],
  },
  {
    id: 'bay_leaf',
    name: 'Bay Leaf',
    category: 'herb',
    equipmentId: 'stockpot',
    flavor: flavor({ BI: 3, HE: 7, EA: 2, PU: 2 }),
    compoundIds: ['c_herb_aroma', 'c_terpene'],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    category: 'seafood',
    equipmentId: 'stockpot',
    flavor: flavor({ SW: 3, SA: 3, UM: 7, LI: 3, TE: 1 }),
    compoundIds: ['c_seafood', 'c_marine'],
  },
  {
    id: 'white_beans',
    name: 'White Beans',
    category: 'legume',
    equipmentId: 'stockpot',
    flavor: flavor({ SW: 2, UM: 2, EA: 4, NU: 3, RI: 3, TE: 1 }),
    compoundIds: ['c_legume', 'c_starch'],
  },
  {
    id: 'beef_broth',
    name: 'Beef Broth',
    category: 'liquid',
    equipmentId: 'stockpot',
    flavor: flavor({ SA: 4, UM: 8, EA: 2, SM: 1, RI: 4, TE: 1 }),
    compoundIds: ['c_broth', 'c_umami_base', 'c_beef'],
  },

  // ---------------------------------------------------------------- cold_station (9)
  {
    id: 'lettuce',
    name: 'Lettuce',
    category: 'vegetable',
    equipmentId: 'cold_station',
    flavor: flavor({ BI: 2, HE: 2, EA: 1, LI: 8, CR: 7, TE: -1 }),
    compoundIds: ['c_green_note'],
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'vegetable',
    equipmentId: 'cold_station',
    flavor: flavor({ HE: 2, FR: 2, LI: 9, CR: 7, TE: -1 }),
    compoundIds: ['c_cucurbit', 'c_green_note'],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'vegetable',
    equipmentId: 'cold_station',
    flavor: flavor({ SW: 4, SO: 4, UM: 5, FR: 3, LI: 4, CR: 3, TE: -1 }),
    compoundIds: ['c_nightshade', 'c_umami_base', 'c_green_note'],
  },
  {
    id: 'mozzarella',
    name: 'Mozzarella',
    category: 'dairy',
    equipmentId: 'cold_station',
    flavor: flavor({ SW: 2, SA: 3, UM: 3, RI: 5, LI: 3, TE: -1 }),
    compoundIds: ['c_dairy_lactone', 'c_fat'],
  },
  {
    id: 'yogurt',
    name: 'Yogurt',
    category: 'dairy',
    equipmentId: 'cold_station',
    flavor: flavor({ SW: 2, SO: 6, UM: 1, RI: 4, LI: 4, TE: -1 }),
    compoundIds: ['c_dairy_lactone', 'c_lactic_ferment'],
  },
  {
    id: 'cream',
    name: 'Heavy Cream',
    category: 'dairy',
    equipmentId: 'cold_station',
    flavor: flavor({ SW: 3, NU: 1, RI: 9, TE: -1 }),
    compoundIds: ['c_dairy_lactone', 'c_fat'],
  },
  {
    id: 'avocado',
    name: 'Avocado',
    category: 'fruit',
    equipmentId: 'cold_station',
    flavor: flavor({ SW: 1, EA: 2, NU: 3, RI: 7, LI: 3, TE: -1 }),
    compoundIds: ['c_fat', 'c_green_note'],
  },
  {
    id: 'feta',
    name: 'Feta',
    category: 'dairy',
    equipmentId: 'cold_station',
    flavor: flavor({ SA: 8, SO: 5, UM: 4, RI: 5, TE: -1 }),
    compoundIds: ['c_dairy_lactone', 'c_lactic_ferment', 'c_aged_ferment'],
  },
  {
    id: 'smoked_salmon',
    name: 'Smoked Salmon',
    category: 'seafood',
    equipmentId: 'cold_station',
    flavor: flavor({ SA: 6, UM: 7, SM: 7, RI: 5, TE: -1 }),
    compoundIds: ['c_seafood', 'c_smoke', 'c_marine'],
  },

  // ---------------------------------------------------------------- pastry_bench (8)
  {
    id: 'sugar',
    name: 'Sugar',
    category: 'sweetener',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 10, CR: 2 }),
    compoundIds: ['c_caramel'],
  },
  {
    id: 'vanilla',
    name: 'Vanilla',
    category: 'flavoring',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 5, FR: 3, EA: 1, NU: 1, RI: 3 }),
    compoundIds: ['c_vanilla_note', 'c_caramel'],
  },
  {
    id: 'yeast',
    name: 'Yeast',
    category: 'leavener',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SO: 1, BI: 2, UM: 4, EA: 3 }),
    compoundIds: ['c_yeast', 'c_umami_base'],
  },
  {
    id: 'cocoa',
    name: 'Cocoa',
    category: 'flavoring',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 1, BI: 7, EA: 4, NU: 3, RI: 5 }),
    compoundIds: ['c_cocoa', 'c_roasted', 'c_pyrazine'],
  },
  {
    id: 'maple_syrup',
    name: 'Maple Syrup',
    category: 'sweetener',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 9, EA: 1, SM: 2, NU: 2, RI: 3 }),
    compoundIds: ['c_caramel', 'c_roasted'],
  },
  {
    id: 'almond',
    name: 'Almond',
    category: 'nut',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 3, BI: 1, NU: 9, RI: 4, CR: 7 }),
    compoundIds: ['c_nutty_note', 'c_benzaldehyde'],
  },
  {
    id: 'cream_cheese',
    name: 'Cream Cheese',
    category: 'dairy',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 2, SA: 3, SO: 4, RI: 7, TE: -1 }),
    compoundIds: ['c_dairy_lactone', 'c_lactic_ferment', 'c_fat'],
  },
  {
    id: 'phyllo',
    name: 'Phyllo Dough',
    category: 'pastry',
    equipmentId: 'pastry_bench',
    flavor: flavor({ SW: 1, NU: 2, LI: 4, CR: 9 }),
    compoundIds: ['c_grain', 'c_starch'],
  },

  // ---------------------------------------------------------------- smoker (7)
  {
    id: 'brisket',
    name: 'Brisket',
    category: 'protein',
    equipmentId: 'smoker',
    flavor: flavor({ SA: 4, UM: 8, SM: 9, RI: 7, TE: 1 }),
    compoundIds: ['c_beef', 'c_smoke', 'c_maillard'],
  },
  {
    id: 'pork_ribs',
    name: 'Pork Ribs',
    category: 'protein',
    equipmentId: 'smoker',
    flavor: flavor({ SW: 3, SA: 3, UM: 7, SM: 8, RI: 7, TE: 1 }),
    compoundIds: ['c_pork', 'c_smoke', 'c_maillard'],
  },
  {
    id: 'smoked_paprika',
    name: 'Smoked Paprika',
    category: 'spice',
    equipmentId: 'smoker',
    flavor: flavor({ SW: 3, BI: 1, EA: 3, SM: 9, PU: 3, HT: 2 }),
    compoundIds: ['c_capsicum', 'c_smoke'],
  },
  {
    id: 'turkey',
    name: 'Smoked Turkey',
    category: 'protein',
    equipmentId: 'smoker',
    flavor: flavor({ SA: 2, UM: 6, SM: 4, RI: 3, LI: 2, TE: 1 }),
    compoundIds: ['c_poultry', 'c_smoke', 'c_maillard'],
  },
  {
    id: 'sausage',
    name: 'Smoked Sausage',
    category: 'protein',
    equipmentId: 'smoker',
    flavor: flavor({ SA: 7, UM: 7, SM: 6, PU: 4, RI: 7, HT: 2, TE: 1 }),
    compoundIds: ['c_pork', 'c_smoke', 'c_warm_spice'],
  },
  {
    id: 'smoked_tofu',
    name: 'Smoked Tofu',
    category: 'legume',
    equipmentId: 'smoker',
    flavor: flavor({ UM: 6, EA: 2, SM: 7, NU: 2, RI: 2 }),
    compoundIds: ['c_soy', 'c_smoke', 'c_legume'],
  },
  {
    id: 'jackfruit',
    name: 'Smoked Jackfruit',
    category: 'fruit',
    equipmentId: 'smoker',
    flavor: flavor({ SW: 5, UM: 3, FR: 6, EA: 2, SM: 4, TE: 1 }),
    compoundIds: ['c_tropical', 'c_smoke'],
  },

  // ---------------------------------------------------------------- wok (9)
  {
    id: 'soy_sauce',
    name: 'Soy Sauce',
    category: 'condiment',
    equipmentId: 'wok',
    flavor: flavor({ SW: 2, SA: 9, UM: 9, EA: 2, RI: 2 }),
    compoundIds: ['c_soy', 'c_aged_ferment', 'c_umami_base'],
  },
  {
    id: 'ginger',
    name: 'Ginger',
    category: 'aromatic',
    equipmentId: 'wok',
    flavor: flavor({ HE: 3, FR: 3, EA: 1, PU: 7, HT: 5 }),
    compoundIds: ['c_ginger_note', 'c_terpene'],
  },
  {
    id: 'bok_choy',
    name: 'Bok Choy',
    category: 'vegetable',
    equipmentId: 'wok',
    flavor: flavor({ BI: 3, UM: 2, HE: 2, EA: 1, LI: 6, CR: 6, TE: 1 }),
    compoundIds: ['c_brassica', 'c_sulfur', 'c_green_note'],
  },
  {
    id: 'sesame_oil',
    name: 'Sesame Oil',
    category: 'fat',
    equipmentId: 'wok',
    flavor: flavor({ EA: 2, SM: 2, NU: 8, RI: 7 }),
    compoundIds: ['c_fat', 'c_nutty_note', 'c_roasted'],
  },
  {
    id: 'rice_noodle',
    name: 'Rice Noodle',
    category: 'grain',
    equipmentId: 'wok',
    flavor: flavor({ SW: 1, NU: 1, LI: 5, TE: 1 }),
    compoundIds: ['c_grain', 'c_starch'],
  },
  {
    id: 'tofu',
    name: 'Tofu',
    category: 'legume',
    equipmentId: 'wok',
    flavor: flavor({ UM: 3, EA: 1, NU: 2, RI: 2, LI: 5 }),
    compoundIds: ['c_soy', 'c_legume'],
  },
  {
    id: 'shrimp_paste',
    name: 'Shrimp Paste',
    category: 'condiment',
    equipmentId: 'wok',
    flavor: flavor({ SA: 8, UM: 9, EA: 3, PU: 7, RI: 2 }),
    compoundIds: ['c_marine', 'c_fish_ferment', 'c_umami_base'],
  },
  {
    id: 'chili_flake',
    name: 'Chili Flake',
    category: 'spice',
    equipmentId: 'wok',
    flavor: flavor({ BI: 1, FR: 2, SM: 3, PU: 5, HT: 9 }),
    compoundIds: ['c_capsicum'],
  },
  {
    id: 'thai_basil',
    name: 'Thai Basil',
    category: 'herb',
    equipmentId: 'wok',
    flavor: flavor({ SW: 2, HE: 9, FR: 3, PU: 4, LI: 3 }),
    compoundIds: ['c_herb_aroma', 'c_terpene', 'c_anise_note'],
  },

  // ---------------------------------------------------------------- fermentation_crock (8)
  {
    id: 'dill_pickle',
    name: 'Dill Pickle',
    category: 'vegetable',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SA: 6, SO: 8, HE: 4, PU: 3, LI: 3, CR: 7, TE: -1 }),
    compoundIds: ['c_lactic_ferment', 'c_cucurbit', 'c_herb_aroma'],
  },
  {
    id: 'kimchi',
    name: 'Kimchi',
    category: 'vegetable',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SA: 6, SO: 7, UM: 5, PU: 7, CR: 5, HT: 6, TE: -1 }),
    compoundIds: ['c_lactic_ferment', 'c_brassica', 'c_capsicum'],
  },
  {
    id: 'miso',
    name: 'Miso',
    category: 'condiment',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SW: 3, SA: 8, UM: 9, EA: 4, RI: 3 }),
    compoundIds: ['c_soy', 'c_aged_ferment', 'c_umami_base'],
  },
  {
    id: 'sauerkraut',
    name: 'Sauerkraut',
    category: 'vegetable',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SA: 5, SO: 8, BI: 2, UM: 2, PU: 3, CR: 6, TE: -1 }),
    compoundIds: ['c_lactic_ferment', 'c_brassica', 'c_sulfur'],
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    category: 'legume',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ BI: 2, UM: 5, EA: 5, NU: 5, RI: 3 }),
    compoundIds: ['c_soy', 'c_legume', 'c_aged_ferment'],
  },
  {
    id: 'kombucha',
    name: 'Kombucha',
    category: 'beverage',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SW: 3, SO: 7, BI: 2, FR: 4, LI: 7, TE: -1 }),
    compoundIds: ['c_lactic_ferment', 'c_yeast', 'c_tea_note'],
  },
  {
    id: 'sour_cream',
    name: 'Sour Cream',
    category: 'dairy',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SW: 1, SA: 2, SO: 6, RI: 7, TE: -1 }),
    compoundIds: ['c_dairy_lactone', 'c_lactic_ferment', 'c_fat'],
  },
  {
    id: 'fish_sauce',
    name: 'Fish Sauce',
    category: 'condiment',
    equipmentId: 'fermentation_crock',
    flavor: flavor({ SA: 10, SO: 2, UM: 10, PU: 6 }),
    compoundIds: ['c_marine', 'c_fish_ferment', 'c_umami_base'],
  },

  // ---------------------------------------------------------------- barista_station (7)
  {
    id: 'coffee',
    name: 'Coffee',
    category: 'beverage',
    equipmentId: 'barista_station',
    flavor: flavor({ SO: 2, BI: 8, EA: 4, SM: 3, NU: 2, RI: 5, TE: 1 }),
    compoundIds: ['c_roasted', 'c_pyrazine', 'c_cocoa'],
  },
  {
    id: 'black_tea',
    name: 'Black Tea',
    category: 'beverage',
    equipmentId: 'barista_station',
    flavor: flavor({ BI: 6, HE: 2, FR: 2, EA: 3, LI: 4, TE: 1 }),
    compoundIds: ['c_tea_note', 'c_tannin'],
  },
  {
    id: 'cinnamon',
    name: 'Cinnamon',
    category: 'spice',
    equipmentId: 'barista_station',
    flavor: flavor({ SW: 5, HE: 3, EA: 1, PU: 5, RI: 2, HT: 2 }),
    compoundIds: ['c_warm_spice', 'c_terpene'],
  },
  {
    id: 'cardamom',
    name: 'Cardamom',
    category: 'spice',
    equipmentId: 'barista_station',
    flavor: flavor({ SW: 2, BI: 2, HE: 7, FR: 3, PU: 5 }),
    compoundIds: ['c_warm_spice', 'c_terpene', 'c_anise_note'],
  },
  {
    id: 'honey',
    name: 'Honey',
    category: 'sweetener',
    equipmentId: 'barista_station',
    flavor: flavor({ SW: 9, HE: 2, FR: 4, RI: 3 }),
    compoundIds: ['c_caramel', 'c_floral_note'],
  },
  {
    id: 'oat_milk',
    name: 'Oat Milk',
    category: 'dairy_alt',
    equipmentId: 'barista_station',
    flavor: flavor({ SW: 3, EA: 2, NU: 3, RI: 4, LI: 5, TE: -1 }),
    compoundIds: ['c_grain', 'c_starch'],
  },
  {
    id: 'coconut_milk',
    name: 'Coconut Milk',
    category: 'dairy_alt',
    equipmentId: 'barista_station',
    flavor: flavor({ SW: 4, FR: 2, NU: 4, RI: 8, LI: 2 }),
    compoundIds: ['c_tropical', 'c_fat', 'c_dairy_lactone'],
  },

  // ---------------------------------------------------------------- spice_rack (7)
  {
    id: 'cumin',
    name: 'Cumin',
    category: 'spice',
    equipmentId: 'spice_rack',
    flavor: flavor({ BI: 3, HE: 2, EA: 7, SM: 3, PU: 6, HT: 1 }),
    compoundIds: ['c_warm_spice', 'c_terpene', 'c_earthy_note'],
  },
  {
    id: 'coriander',
    name: 'Coriander',
    category: 'spice',
    equipmentId: 'spice_rack',
    flavor: flavor({ SW: 2, HE: 5, FR: 4, EA: 1, PU: 3, NU: 2 }),
    compoundIds: ['c_warm_spice', 'c_terpene', 'c_citrus'],
  },
  {
    id: 'turmeric',
    name: 'Turmeric',
    category: 'spice',
    equipmentId: 'spice_rack',
    flavor: flavor({ BI: 5, EA: 7, PU: 4, HT: 1 }),
    compoundIds: ['c_ginger_note', 'c_terpene', 'c_earthy_note'],
  },
  {
    id: 'oregano',
    name: 'Oregano',
    category: 'herb',
    equipmentId: 'spice_rack',
    flavor: flavor({ BI: 3, HE: 9, EA: 2, PU: 4, LI: 2 }),
    compoundIds: ['c_herb_aroma', 'c_terpene'],
  },
  {
    id: 'thyme',
    name: 'Thyme',
    category: 'herb',
    equipmentId: 'spice_rack',
    flavor: flavor({ BI: 2, HE: 8, FR: 1, EA: 2, PU: 3 }),
    compoundIds: ['c_herb_aroma', 'c_terpene'],
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    category: 'herb',
    equipmentId: 'spice_rack',
    flavor: flavor({ BI: 4, HE: 9, FR: 1, EA: 2, PU: 4 }),
    compoundIds: ['c_herb_aroma', 'c_terpene', 'c_pine_note'],
  },
  {
    id: 'paprika',
    name: 'Paprika',
    category: 'spice',
    equipmentId: 'spice_rack',
    flavor: flavor({ SW: 4, BI: 1, FR: 2, EA: 3, SM: 1, PU: 2, HT: 1 }),
    compoundIds: ['c_capsicum', 'c_earthy_note'],
  },
];

/**
 * Assigns purchaseIndex 0-99: equipment groups in EQUIPMENT_IDS order, and
 * within each group in authored order.
 */
export function buildIngredientList(): Ingredient[] {
  const ordered = EQUIPMENT_IDS.flatMap((equipmentId) =>
    INGREDIENT_DEFINITIONS.filter((definition) => definition.equipmentId === equipmentId),
  );

  if (ordered.length !== INGREDIENT_DEFINITIONS.length) {
    throw new Error('ingredient definitions contain an unknown equipmentId');
  }

  return ordered.map((definition, purchaseIndex) => ({ ...definition, purchaseIndex }));
}
